name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        ./gradlew :module:assembleRelease
        # Find the generated zip file anywhere inside 'out' and rename it
        ZIP_FILE=$(find out -type f -name "*.zip" | head -n 1)
        if [ -z "$ZIP_FILE" ]; then
          echo "❌ No Magisk module zip found!"
          exit 1
        fi
        NEW_NAME="out/zygisk-il2cppdumper-${{ github.event.inputs.package_name }}.zip"
        mv "$ZIP_FILE" "$NEW_NAME"
        echo "✅ Renamed output to $NEW_NAME"
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
        path: out/zygisk-il2cppdumper-${{ github.event.inputs.package_name }}.zip
